################################################################################
# Ocarina travis-ci configuration file.
# This script compiles and test Ocarina for Linux and OS X targets
#
# Note: this travis-ci script is adapted from
# https://github.com/AdaCore/Ada_Drivers_Library
#
# Thanks to AdaCore for providing it

################################################################################
# Note: we are using 'generic' as a language. We need GNAT to compile
# Ocarina, and Python to run Ocarina testsuite. We install a specific
# GNAT GPL release to compile and run everything.

language: generic
osx_image: xcode8.3

# Global variables
env:
  global:
    - TOOLS_DIR=$HOME/build_tools
    - INSTALL_DIR=$HOME/tools

################################################################################
# Host to run the various tests
os:
  - linux
  - osx

################################################################################
# Install the build environment, derived from travis default installation

# 1/ Cache directory that allows us to not download GNAT GPL every time,
# speeding up the process.

cache:
  directories:
  - $HOME/build_tools
  - $HOME/tools

# 2/ Check Python installation

before_install:
- which python

# 3/ Install GNAT

install:
  - git clone https://github.com/OpenAADL/ocarina-build.git ; ( cd ocarina-build ; ./build_ocarina.sh --install-gnat-ce ; cd $HOME)
  - export PATH=$HOME/tools/bin:$PATH
  - echo $PATH

################################################################################
# Main processing starts here

script:
  # Show GNAT version for the record
  - gcc --version
  - gnatls -v

  # Just build
  - ( cd ocarina-build ; ./build_ocarina.sh --scenario=travis-ci )

# Codecov.io
after_success:
  - bash <(curl -s https://codecov.io/bash)

################################################################################
#

before_deploy:
  - export OCARINA_SRC=$(find . -name "*tar.gz")
  - echo $OCARINA_SRC
  - export OCARINA_BIN=$(find . -name "*tgz")
  - echo $OCARINA_BIN

deploy:
  provider: releases
  api_key:
    secure: JIs5VZq+T0m42jasHpuDHXjJwgmQNGDaNJos9xHG01b5tvrG9NRIPjB4AFh1RiJBQ8LYFRpcRkrEzbAHs9H4jh7zLrdaAGRo6v0G/h5aowWNGoTiT6sMy5ATX6cuMO/treCEWWEUpUsDy5GSebsRkGhbMjH3d2kZ3933SJIg+kI=
  skip_cleanup: true
  file:
    - "${OCARINA_SRC}"
    - "${OCARINA_BIN}"
  on:
    tags: true
    all_branches: true
