#ifndef __OCARINA_GENERATED_ACTIVITY_H_
#define __OCARINA_GENERATED_ACTIVITY_H_ 
#include <request.h>
/*****************************************************/

/*  This file was automatically generated by Ocarina */

/*  Do NOT hand-modify this file, as your            */

/*  changes will be lost when you re-run Ocarina     */

/*****************************************************/

void accelero_thread_deliver 
    (__po_hi_request_t* request);

void* accelero_thread_job (void);

void magneto_thread_deliver 
    (__po_hi_request_t* request);

void* magneto_thread_job (void);

void gyro_thread_deliver 
    (__po_hi_request_t* request);

void* gyro_thread_job (void);

void attitude_calculation_thread_deliver 
    (__po_hi_request_t* request);

void* attitude_calculation_thread_job (void);

void __po_hi_main_deliver 
    (__po_hi_request_t* request);

#endif
