#include <types.h>
#include <po_hi_types.h>
#include <po_hi_marshallers.h>
/*****************************************************/
/*  This file was automatically generated by Ocarina */
/*  Do NOT hand-modify this file, as your            */
/*  changes will be lost when you re-run Ocarina     */
/*****************************************************/
void __po_hi_marshall_type_float32_type_aadl 
    (ahrs__data_types__float32_type_aadl value,
    __po_hi_msg_t* message,
    __po_hi_uint32_t* offset)
{

  __po_hi_marshall_array (&(value), message, 4, offset);
}

void __po_hi_unmarshall_type_float32_type_aadl 
    (ahrs__data_types__float32_type_aadl* value,
    __po_hi_msg_t* message,
    __po_hi_uint32_t* offset)
{

  __po_hi_unmarshall_array (value, message, 4, offset);
}

void __po_hi_marshall_request_accelero_thread_acc_in_data_x 
    (__po_hi_request_t* request,
    __po_hi_msg_t* message,
    __po_hi_uint32_t* offset)
{

  __po_hi_marshall_type_float32_type_aadl (request->vars.accelero_thread_global_acc_in_data_x.accelero_thread_global_acc_in_data_x, message, offset);
}

void __po_hi_unmarshall_request_accelero_thread_acc_in_data_x 
    (__po_hi_request_t* request,
    __po_hi_msg_t* message,
    __po_hi_uint32_t* offset)
{

  __po_hi_unmarshall_type_float32_type_aadl (&(request->vars.accelero_thread_global_acc_in_data_x.accelero_thread_global_acc_in_data_x), message, offset);
}

void __po_hi_marshall_request_accelero_thread_acc_in_data_y 
    (__po_hi_request_t* request,
    __po_hi_msg_t* message,
    __po_hi_uint32_t* offset)
{

  __po_hi_marshall_type_float32_type_aadl (request->vars.accelero_thread_global_acc_in_data_y.accelero_thread_global_acc_in_data_y, message, offset);
}

void __po_hi_unmarshall_request_accelero_thread_acc_in_data_y 
    (__po_hi_request_t* request,
    __po_hi_msg_t* message,
    __po_hi_uint32_t* offset)
{

  __po_hi_unmarshall_type_float32_type_aadl (&(request->vars.accelero_thread_global_acc_in_data_y.accelero_thread_global_acc_in_data_y), message, offset);
}

void __po_hi_marshall_request_accelero_thread_acc_in_data_z 
    (__po_hi_request_t* request,
    __po_hi_msg_t* message,
    __po_hi_uint32_t* offset)
{

  __po_hi_marshall_type_float32_type_aadl (request->vars.accelero_thread_global_acc_in_data_z.accelero_thread_global_acc_in_data_z, message, offset);
}

void __po_hi_unmarshall_request_accelero_thread_acc_in_data_z 
    (__po_hi_request_t* request,
    __po_hi_msg_t* message,
    __po_hi_uint32_t* offset)
{

  __po_hi_unmarshall_type_float32_type_aadl (&(request->vars.accelero_thread_global_acc_in_data_z.accelero_thread_global_acc_in_data_z), message, offset);
}

void __po_hi_marshall_request_accelero_thread_acc_out_data_x 
    (__po_hi_request_t* request,
    __po_hi_msg_t* message,
    __po_hi_uint32_t* offset)
{

  __po_hi_marshall_type_float32_type_aadl (request->vars.accelero_thread_global_acc_out_data_x.accelero_thread_global_acc_out_data_x, message, offset);
}

void __po_hi_unmarshall_request_accelero_thread_acc_out_data_x 
    (__po_hi_request_t* request,
    __po_hi_msg_t* message,
    __po_hi_uint32_t* offset)
{

  __po_hi_unmarshall_type_float32_type_aadl (&(request->vars.accelero_thread_global_acc_out_data_x.accelero_thread_global_acc_out_data_x), message, offset);
}

void __po_hi_marshall_request_accelero_thread_acc_out_data_y 
    (__po_hi_request_t* request,
    __po_hi_msg_t* message,
    __po_hi_uint32_t* offset)
{

  __po_hi_marshall_type_float32_type_aadl (request->vars.accelero_thread_global_acc_out_data_y.accelero_thread_global_acc_out_data_y, message, offset);
}

void __po_hi_unmarshall_request_accelero_thread_acc_out_data_y 
    (__po_hi_request_t* request,
    __po_hi_msg_t* message,
    __po_hi_uint32_t* offset)
{

  __po_hi_unmarshall_type_float32_type_aadl (&(request->vars.accelero_thread_global_acc_out_data_y.accelero_thread_global_acc_out_data_y), message, offset);
}

void __po_hi_marshall_request_accelero_thread_acc_out_data_z 
    (__po_hi_request_t* request,
    __po_hi_msg_t* message,
    __po_hi_uint32_t* offset)
{

  __po_hi_marshall_type_float32_type_aadl (request->vars.accelero_thread_global_acc_out_data_z.accelero_thread_global_acc_out_data_z, message, offset);
}

void __po_hi_unmarshall_request_accelero_thread_acc_out_data_z 
    (__po_hi_request_t* request,
    __po_hi_msg_t* message,
    __po_hi_uint32_t* offset)
{

  __po_hi_unmarshall_type_float32_type_aadl (&(request->vars.accelero_thread_global_acc_out_data_z.accelero_thread_global_acc_out_data_z), message, offset);
}

void __po_hi_marshall_request_magneto_thread_mag_in_data_x 
    (__po_hi_request_t* request,
    __po_hi_msg_t* message,
    __po_hi_uint32_t* offset)
{

  __po_hi_marshall_type_float32_type_aadl (request->vars.magneto_thread_global_mag_in_data_x.magneto_thread_global_mag_in_data_x, message, offset);
}

void __po_hi_unmarshall_request_magneto_thread_mag_in_data_x 
    (__po_hi_request_t* request,
    __po_hi_msg_t* message,
    __po_hi_uint32_t* offset)
{

  __po_hi_unmarshall_type_float32_type_aadl (&(request->vars.magneto_thread_global_mag_in_data_x.magneto_thread_global_mag_in_data_x), message, offset);
}

void __po_hi_marshall_request_magneto_thread_mag_in_data_y 
    (__po_hi_request_t* request,
    __po_hi_msg_t* message,
    __po_hi_uint32_t* offset)
{

  __po_hi_marshall_type_float32_type_aadl (request->vars.magneto_thread_global_mag_in_data_y.magneto_thread_global_mag_in_data_y, message, offset);
}

void __po_hi_unmarshall_request_magneto_thread_mag_in_data_y 
    (__po_hi_request_t* request,
    __po_hi_msg_t* message,
    __po_hi_uint32_t* offset)
{

  __po_hi_unmarshall_type_float32_type_aadl (&(request->vars.magneto_thread_global_mag_in_data_y.magneto_thread_global_mag_in_data_y), message, offset);
}

void __po_hi_marshall_request_magneto_thread_mag_in_data_z 
    (__po_hi_request_t* request,
    __po_hi_msg_t* message,
    __po_hi_uint32_t* offset)
{

  __po_hi_marshall_type_float32_type_aadl (request->vars.magneto_thread_global_mag_in_data_z.magneto_thread_global_mag_in_data_z, message, offset);
}

void __po_hi_unmarshall_request_magneto_thread_mag_in_data_z 
    (__po_hi_request_t* request,
    __po_hi_msg_t* message,
    __po_hi_uint32_t* offset)
{

  __po_hi_unmarshall_type_float32_type_aadl (&(request->vars.magneto_thread_global_mag_in_data_z.magneto_thread_global_mag_in_data_z), message, offset);
}

void __po_hi_marshall_request_magneto_thread_mag_out_data_x 
    (__po_hi_request_t* request,
    __po_hi_msg_t* message,
    __po_hi_uint32_t* offset)
{

  __po_hi_marshall_type_float32_type_aadl (request->vars.magneto_thread_global_mag_out_data_x.magneto_thread_global_mag_out_data_x, message, offset);
}

void __po_hi_unmarshall_request_magneto_thread_mag_out_data_x 
    (__po_hi_request_t* request,
    __po_hi_msg_t* message,
    __po_hi_uint32_t* offset)
{

  __po_hi_unmarshall_type_float32_type_aadl (&(request->vars.magneto_thread_global_mag_out_data_x.magneto_thread_global_mag_out_data_x), message, offset);
}

void __po_hi_marshall_request_magneto_thread_mag_out_data_y 
    (__po_hi_request_t* request,
    __po_hi_msg_t* message,
    __po_hi_uint32_t* offset)
{

  __po_hi_marshall_type_float32_type_aadl (request->vars.magneto_thread_global_mag_out_data_y.magneto_thread_global_mag_out_data_y, message, offset);
}

void __po_hi_unmarshall_request_magneto_thread_mag_out_data_y 
    (__po_hi_request_t* request,
    __po_hi_msg_t* message,
    __po_hi_uint32_t* offset)
{

  __po_hi_unmarshall_type_float32_type_aadl (&(request->vars.magneto_thread_global_mag_out_data_y.magneto_thread_global_mag_out_data_y), message, offset);
}

void __po_hi_marshall_request_magneto_thread_mag_out_data_z 
    (__po_hi_request_t* request,
    __po_hi_msg_t* message,
    __po_hi_uint32_t* offset)
{

  __po_hi_marshall_type_float32_type_aadl (request->vars.magneto_thread_global_mag_out_data_z.magneto_thread_global_mag_out_data_z, message, offset);
}

void __po_hi_unmarshall_request_magneto_thread_mag_out_data_z 
    (__po_hi_request_t* request,
    __po_hi_msg_t* message,
    __po_hi_uint32_t* offset)
{

  __po_hi_unmarshall_type_float32_type_aadl (&(request->vars.magneto_thread_global_mag_out_data_z.magneto_thread_global_mag_out_data_z), message, offset);
}

void __po_hi_marshall_request_gyro_thread_gyro_in_data_x 
    (__po_hi_request_t* request,
    __po_hi_msg_t* message,
    __po_hi_uint32_t* offset)
{

  __po_hi_marshall_type_float32_type_aadl (request->vars.gyro_thread_global_gyro_in_data_x.gyro_thread_global_gyro_in_data_x, message, offset);
}

void __po_hi_unmarshall_request_gyro_thread_gyro_in_data_x 
    (__po_hi_request_t* request,
    __po_hi_msg_t* message,
    __po_hi_uint32_t* offset)
{

  __po_hi_unmarshall_type_float32_type_aadl (&(request->vars.gyro_thread_global_gyro_in_data_x.gyro_thread_global_gyro_in_data_x), message, offset);
}

void __po_hi_marshall_request_gyro_thread_gyro_in_data_y 
    (__po_hi_request_t* request,
    __po_hi_msg_t* message,
    __po_hi_uint32_t* offset)
{

  __po_hi_marshall_type_float32_type_aadl (request->vars.gyro_thread_global_gyro_in_data_y.gyro_thread_global_gyro_in_data_y, message, offset);
}

void __po_hi_unmarshall_request_gyro_thread_gyro_in_data_y 
    (__po_hi_request_t* request,
    __po_hi_msg_t* message,
    __po_hi_uint32_t* offset)
{

  __po_hi_unmarshall_type_float32_type_aadl (&(request->vars.gyro_thread_global_gyro_in_data_y.gyro_thread_global_gyro_in_data_y), message, offset);
}

void __po_hi_marshall_request_gyro_thread_gyro_in_data_z 
    (__po_hi_request_t* request,
    __po_hi_msg_t* message,
    __po_hi_uint32_t* offset)
{

  __po_hi_marshall_type_float32_type_aadl (request->vars.gyro_thread_global_gyro_in_data_z.gyro_thread_global_gyro_in_data_z, message, offset);
}

void __po_hi_unmarshall_request_gyro_thread_gyro_in_data_z 
    (__po_hi_request_t* request,
    __po_hi_msg_t* message,
    __po_hi_uint32_t* offset)
{

  __po_hi_unmarshall_type_float32_type_aadl (&(request->vars.gyro_thread_global_gyro_in_data_z.gyro_thread_global_gyro_in_data_z), message, offset);
}

void __po_hi_marshall_request_gyro_thread_gyro_out_data_x 
    (__po_hi_request_t* request,
    __po_hi_msg_t* message,
    __po_hi_uint32_t* offset)
{

  __po_hi_marshall_type_float32_type_aadl (request->vars.gyro_thread_global_gyro_out_data_x.gyro_thread_global_gyro_out_data_x, message, offset);
}

void __po_hi_unmarshall_request_gyro_thread_gyro_out_data_x 
    (__po_hi_request_t* request,
    __po_hi_msg_t* message,
    __po_hi_uint32_t* offset)
{

  __po_hi_unmarshall_type_float32_type_aadl (&(request->vars.gyro_thread_global_gyro_out_data_x.gyro_thread_global_gyro_out_data_x), message, offset);
}

void __po_hi_marshall_request_gyro_thread_gyro_out_data_y 
    (__po_hi_request_t* request,
    __po_hi_msg_t* message,
    __po_hi_uint32_t* offset)
{

  __po_hi_marshall_type_float32_type_aadl (request->vars.gyro_thread_global_gyro_out_data_y.gyro_thread_global_gyro_out_data_y, message, offset);
}

void __po_hi_unmarshall_request_gyro_thread_gyro_out_data_y 
    (__po_hi_request_t* request,
    __po_hi_msg_t* message,
    __po_hi_uint32_t* offset)
{

  __po_hi_unmarshall_type_float32_type_aadl (&(request->vars.gyro_thread_global_gyro_out_data_y.gyro_thread_global_gyro_out_data_y), message, offset);
}

void __po_hi_marshall_request_gyro_thread_gyro_out_data_z 
    (__po_hi_request_t* request,
    __po_hi_msg_t* message,
    __po_hi_uint32_t* offset)
{

  __po_hi_marshall_type_float32_type_aadl (request->vars.gyro_thread_global_gyro_out_data_z.gyro_thread_global_gyro_out_data_z, message, offset);
}

void __po_hi_unmarshall_request_gyro_thread_gyro_out_data_z 
    (__po_hi_request_t* request,
    __po_hi_msg_t* message,
    __po_hi_uint32_t* offset)
{

  __po_hi_unmarshall_type_float32_type_aadl (&(request->vars.gyro_thread_global_gyro_out_data_z.gyro_thread_global_gyro_out_data_z), message, offset);
}

void __po_hi_marshall_request_attitude_calculation_thread_acc_in_data_x 
    (__po_hi_request_t* request,
    __po_hi_msg_t* message,
    __po_hi_uint32_t* offset)
{

  __po_hi_marshall_type_float32_type_aadl (request->vars.attitude_calculation_thread_global_acc_in_data_x.attitude_calculation_thread_global_acc_in_data_x, message, offset);
}

void __po_hi_unmarshall_request_attitude_calculation_thread_acc_in_data_x 
    (__po_hi_request_t* request,
    __po_hi_msg_t* message,
    __po_hi_uint32_t* offset)
{

  __po_hi_unmarshall_type_float32_type_aadl (&(request->vars.attitude_calculation_thread_global_acc_in_data_x.attitude_calculation_thread_global_acc_in_data_x), message, offset);
}

void __po_hi_marshall_request_attitude_calculation_thread_acc_in_data_y 
    (__po_hi_request_t* request,
    __po_hi_msg_t* message,
    __po_hi_uint32_t* offset)
{

  __po_hi_marshall_type_float32_type_aadl (request->vars.attitude_calculation_thread_global_acc_in_data_y.attitude_calculation_thread_global_acc_in_data_y, message, offset);
}

void __po_hi_unmarshall_request_attitude_calculation_thread_acc_in_data_y 
    (__po_hi_request_t* request,
    __po_hi_msg_t* message,
    __po_hi_uint32_t* offset)
{

  __po_hi_unmarshall_type_float32_type_aadl (&(request->vars.attitude_calculation_thread_global_acc_in_data_y.attitude_calculation_thread_global_acc_in_data_y), message, offset);
}

void __po_hi_marshall_request_attitude_calculation_thread_acc_in_data_z 
    (__po_hi_request_t* request,
    __po_hi_msg_t* message,
    __po_hi_uint32_t* offset)
{

  __po_hi_marshall_type_float32_type_aadl (request->vars.attitude_calculation_thread_global_acc_in_data_z.attitude_calculation_thread_global_acc_in_data_z, message, offset);
}

void __po_hi_unmarshall_request_attitude_calculation_thread_acc_in_data_z 
    (__po_hi_request_t* request,
    __po_hi_msg_t* message,
    __po_hi_uint32_t* offset)
{

  __po_hi_unmarshall_type_float32_type_aadl (&(request->vars.attitude_calculation_thread_global_acc_in_data_z.attitude_calculation_thread_global_acc_in_data_z), message, offset);
}

void __po_hi_marshall_request_attitude_calculation_thread_mag_in_data_x 
    (__po_hi_request_t* request,
    __po_hi_msg_t* message,
    __po_hi_uint32_t* offset)
{

  __po_hi_marshall_type_float32_type_aadl (request->vars.attitude_calculation_thread_global_mag_in_data_x.attitude_calculation_thread_global_mag_in_data_x, message, offset);
}

void __po_hi_unmarshall_request_attitude_calculation_thread_mag_in_data_x 
    (__po_hi_request_t* request,
    __po_hi_msg_t* message,
    __po_hi_uint32_t* offset)
{

  __po_hi_unmarshall_type_float32_type_aadl (&(request->vars.attitude_calculation_thread_global_mag_in_data_x.attitude_calculation_thread_global_mag_in_data_x), message, offset);
}

void __po_hi_marshall_request_attitude_calculation_thread_mag_in_data_y 
    (__po_hi_request_t* request,
    __po_hi_msg_t* message,
    __po_hi_uint32_t* offset)
{

  __po_hi_marshall_type_float32_type_aadl (request->vars.attitude_calculation_thread_global_mag_in_data_y.attitude_calculation_thread_global_mag_in_data_y, message, offset);
}

void __po_hi_unmarshall_request_attitude_calculation_thread_mag_in_data_y 
    (__po_hi_request_t* request,
    __po_hi_msg_t* message,
    __po_hi_uint32_t* offset)
{

  __po_hi_unmarshall_type_float32_type_aadl (&(request->vars.attitude_calculation_thread_global_mag_in_data_y.attitude_calculation_thread_global_mag_in_data_y), message, offset);
}

void __po_hi_marshall_request_attitude_calculation_thread_mag_in_data_z 
    (__po_hi_request_t* request,
    __po_hi_msg_t* message,
    __po_hi_uint32_t* offset)
{

  __po_hi_marshall_type_float32_type_aadl (request->vars.attitude_calculation_thread_global_mag_in_data_z.attitude_calculation_thread_global_mag_in_data_z, message, offset);
}

void __po_hi_unmarshall_request_attitude_calculation_thread_mag_in_data_z 
    (__po_hi_request_t* request,
    __po_hi_msg_t* message,
    __po_hi_uint32_t* offset)
{

  __po_hi_unmarshall_type_float32_type_aadl (&(request->vars.attitude_calculation_thread_global_mag_in_data_z.attitude_calculation_thread_global_mag_in_data_z), message, offset);
}

void __po_hi_marshall_request_attitude_calculation_thread_gyro_in_data_x 
    (__po_hi_request_t* request,
    __po_hi_msg_t* message,
    __po_hi_uint32_t* offset)
{

  __po_hi_marshall_type_float32_type_aadl (request->vars.attitude_calculation_thread_global_gyro_in_data_x.attitude_calculation_thread_global_gyro_in_data_x, message, offset);
}

void __po_hi_unmarshall_request_attitude_calculation_thread_gyro_in_data_x 
    (__po_hi_request_t* request,
    __po_hi_msg_t* message,
    __po_hi_uint32_t* offset)
{

  __po_hi_unmarshall_type_float32_type_aadl (&(request->vars.attitude_calculation_thread_global_gyro_in_data_x.attitude_calculation_thread_global_gyro_in_data_x), message, offset);
}

void __po_hi_marshall_request_attitude_calculation_thread_gyro_in_data_y 
    (__po_hi_request_t* request,
    __po_hi_msg_t* message,
    __po_hi_uint32_t* offset)
{

  __po_hi_marshall_type_float32_type_aadl (request->vars.attitude_calculation_thread_global_gyro_in_data_y.attitude_calculation_thread_global_gyro_in_data_y, message, offset);
}

void __po_hi_unmarshall_request_attitude_calculation_thread_gyro_in_data_y 
    (__po_hi_request_t* request,
    __po_hi_msg_t* message,
    __po_hi_uint32_t* offset)
{

  __po_hi_unmarshall_type_float32_type_aadl (&(request->vars.attitude_calculation_thread_global_gyro_in_data_y.attitude_calculation_thread_global_gyro_in_data_y), message, offset);
}

void __po_hi_marshall_request_attitude_calculation_thread_gyro_in_data_z 
    (__po_hi_request_t* request,
    __po_hi_msg_t* message,
    __po_hi_uint32_t* offset)
{

  __po_hi_marshall_type_float32_type_aadl (request->vars.attitude_calculation_thread_global_gyro_in_data_z.attitude_calculation_thread_global_gyro_in_data_z, message, offset);
}

void __po_hi_unmarshall_request_attitude_calculation_thread_gyro_in_data_z 
    (__po_hi_request_t* request,
    __po_hi_msg_t* message,
    __po_hi_uint32_t* offset)
{

  __po_hi_unmarshall_type_float32_type_aadl (&(request->vars.attitude_calculation_thread_global_gyro_in_data_z.attitude_calculation_thread_global_gyro_in_data_z), message, offset);
}

void __po_hi_marshall_request 
    (__po_hi_request_t* request,
    __po_hi_msg_t* message)
{
  __po_hi_uint32_t offset;

  offset = 0;
  __po_hi_marshall_port (request->port, message);
  switch (request->port)
  {
    case accelero_thread_global_acc_in_data_x:
    {
      __po_hi_marshall_request_accelero_thread_acc_in_data_x (request, message, &(offset));

      break;
    }
    case accelero_thread_global_acc_in_data_y:
    {
      __po_hi_marshall_request_accelero_thread_acc_in_data_y (request, message, &(offset));

      break;
    }
    case accelero_thread_global_acc_in_data_z:
    {
      __po_hi_marshall_request_accelero_thread_acc_in_data_z (request, message, &(offset));

      break;
    }
    case accelero_thread_global_acc_out_data_x:
    {
      __po_hi_marshall_request_accelero_thread_acc_out_data_x (request, message, &(offset));

      break;
    }
    case accelero_thread_global_acc_out_data_y:
    {
      __po_hi_marshall_request_accelero_thread_acc_out_data_y (request, message, &(offset));

      break;
    }
    case accelero_thread_global_acc_out_data_z:
    {
      __po_hi_marshall_request_accelero_thread_acc_out_data_z (request, message, &(offset));

      break;
    }
    case magneto_thread_global_mag_in_data_x:
    {
      __po_hi_marshall_request_magneto_thread_mag_in_data_x (request, message, &(offset));

      break;
    }
    case magneto_thread_global_mag_in_data_y:
    {
      __po_hi_marshall_request_magneto_thread_mag_in_data_y (request, message, &(offset));

      break;
    }
    case magneto_thread_global_mag_in_data_z:
    {
      __po_hi_marshall_request_magneto_thread_mag_in_data_z (request, message, &(offset));

      break;
    }
    case magneto_thread_global_mag_out_data_x:
    {
      __po_hi_marshall_request_magneto_thread_mag_out_data_x (request, message, &(offset));

      break;
    }
    case magneto_thread_global_mag_out_data_y:
    {
      __po_hi_marshall_request_magneto_thread_mag_out_data_y (request, message, &(offset));

      break;
    }
    case magneto_thread_global_mag_out_data_z:
    {
      __po_hi_marshall_request_magneto_thread_mag_out_data_z (request, message, &(offset));

      break;
    }
    case gyro_thread_global_gyro_in_data_x:
    {
      __po_hi_marshall_request_gyro_thread_gyro_in_data_x (request, message, &(offset));

      break;
    }
    case gyro_thread_global_gyro_in_data_y:
    {
      __po_hi_marshall_request_gyro_thread_gyro_in_data_y (request, message, &(offset));

      break;
    }
    case gyro_thread_global_gyro_in_data_z:
    {
      __po_hi_marshall_request_gyro_thread_gyro_in_data_z (request, message, &(offset));

      break;
    }
    case gyro_thread_global_gyro_out_data_x:
    {
      __po_hi_marshall_request_gyro_thread_gyro_out_data_x (request, message, &(offset));

      break;
    }
    case gyro_thread_global_gyro_out_data_y:
    {
      __po_hi_marshall_request_gyro_thread_gyro_out_data_y (request, message, &(offset));

      break;
    }
    case gyro_thread_global_gyro_out_data_z:
    {
      __po_hi_marshall_request_gyro_thread_gyro_out_data_z (request, message, &(offset));

      break;
    }
    case attitude_calculation_thread_global_acc_in_data_x:
    {
      __po_hi_marshall_request_attitude_calculation_thread_acc_in_data_x (request, message, &(offset));

      break;
    }
    case attitude_calculation_thread_global_acc_in_data_y:
    {
      __po_hi_marshall_request_attitude_calculation_thread_acc_in_data_y (request, message, &(offset));

      break;
    }
    case attitude_calculation_thread_global_acc_in_data_z:
    {
      __po_hi_marshall_request_attitude_calculation_thread_acc_in_data_z (request, message, &(offset));

      break;
    }
    case attitude_calculation_thread_global_mag_in_data_x:
    {
      __po_hi_marshall_request_attitude_calculation_thread_mag_in_data_x (request, message, &(offset));

      break;
    }
    case attitude_calculation_thread_global_mag_in_data_y:
    {
      __po_hi_marshall_request_attitude_calculation_thread_mag_in_data_y (request, message, &(offset));

      break;
    }
    case attitude_calculation_thread_global_mag_in_data_z:
    {
      __po_hi_marshall_request_attitude_calculation_thread_mag_in_data_z (request, message, &(offset));

      break;
    }
    case attitude_calculation_thread_global_gyro_in_data_x:
    {
      __po_hi_marshall_request_attitude_calculation_thread_gyro_in_data_x (request, message, &(offset));

      break;
    }
    case attitude_calculation_thread_global_gyro_in_data_y:
    {
      __po_hi_marshall_request_attitude_calculation_thread_gyro_in_data_y (request, message, &(offset));

      break;
    }
    case attitude_calculation_thread_global_gyro_in_data_z:
    {
      __po_hi_marshall_request_attitude_calculation_thread_gyro_in_data_z (request, message, &(offset));

      break;
    }
    default:
    {
      break;
    }
  }
}

void __po_hi_unmarshall_request 
    (__po_hi_request_t* request,
    __po_hi_msg_t* message)
{
  __po_hi_uint32_t offset;

  offset = 0;
  __po_hi_unmarshall_port (&(request->port), message);
  switch (request->port)
  {
    case accelero_thread_global_acc_in_data_x:
    {
      __po_hi_unmarshall_request_accelero_thread_acc_in_data_x (request, message, &(offset));

      break;
    }
    case accelero_thread_global_acc_in_data_y:
    {
      __po_hi_unmarshall_request_accelero_thread_acc_in_data_y (request, message, &(offset));

      break;
    }
    case accelero_thread_global_acc_in_data_z:
    {
      __po_hi_unmarshall_request_accelero_thread_acc_in_data_z (request, message, &(offset));

      break;
    }
    case accelero_thread_global_acc_out_data_x:
    {
      __po_hi_unmarshall_request_accelero_thread_acc_out_data_x (request, message, &(offset));

      break;
    }
    case accelero_thread_global_acc_out_data_y:
    {
      __po_hi_unmarshall_request_accelero_thread_acc_out_data_y (request, message, &(offset));

      break;
    }
    case accelero_thread_global_acc_out_data_z:
    {
      __po_hi_unmarshall_request_accelero_thread_acc_out_data_z (request, message, &(offset));

      break;
    }
    case magneto_thread_global_mag_in_data_x:
    {
      __po_hi_unmarshall_request_magneto_thread_mag_in_data_x (request, message, &(offset));

      break;
    }
    case magneto_thread_global_mag_in_data_y:
    {
      __po_hi_unmarshall_request_magneto_thread_mag_in_data_y (request, message, &(offset));

      break;
    }
    case magneto_thread_global_mag_in_data_z:
    {
      __po_hi_unmarshall_request_magneto_thread_mag_in_data_z (request, message, &(offset));

      break;
    }
    case magneto_thread_global_mag_out_data_x:
    {
      __po_hi_unmarshall_request_magneto_thread_mag_out_data_x (request, message, &(offset));

      break;
    }
    case magneto_thread_global_mag_out_data_y:
    {
      __po_hi_unmarshall_request_magneto_thread_mag_out_data_y (request, message, &(offset));

      break;
    }
    case magneto_thread_global_mag_out_data_z:
    {
      __po_hi_unmarshall_request_magneto_thread_mag_out_data_z (request, message, &(offset));

      break;
    }
    case gyro_thread_global_gyro_in_data_x:
    {
      __po_hi_unmarshall_request_gyro_thread_gyro_in_data_x (request, message, &(offset));

      break;
    }
    case gyro_thread_global_gyro_in_data_y:
    {
      __po_hi_unmarshall_request_gyro_thread_gyro_in_data_y (request, message, &(offset));

      break;
    }
    case gyro_thread_global_gyro_in_data_z:
    {
      __po_hi_unmarshall_request_gyro_thread_gyro_in_data_z (request, message, &(offset));

      break;
    }
    case gyro_thread_global_gyro_out_data_x:
    {
      __po_hi_unmarshall_request_gyro_thread_gyro_out_data_x (request, message, &(offset));

      break;
    }
    case gyro_thread_global_gyro_out_data_y:
    {
      __po_hi_unmarshall_request_gyro_thread_gyro_out_data_y (request, message, &(offset));

      break;
    }
    case gyro_thread_global_gyro_out_data_z:
    {
      __po_hi_unmarshall_request_gyro_thread_gyro_out_data_z (request, message, &(offset));

      break;
    }
    case attitude_calculation_thread_global_acc_in_data_x:
    {
      __po_hi_unmarshall_request_attitude_calculation_thread_acc_in_data_x (request, message, &(offset));

      break;
    }
    case attitude_calculation_thread_global_acc_in_data_y:
    {
      __po_hi_unmarshall_request_attitude_calculation_thread_acc_in_data_y (request, message, &(offset));

      break;
    }
    case attitude_calculation_thread_global_acc_in_data_z:
    {
      __po_hi_unmarshall_request_attitude_calculation_thread_acc_in_data_z (request, message, &(offset));

      break;
    }
    case attitude_calculation_thread_global_mag_in_data_x:
    {
      __po_hi_unmarshall_request_attitude_calculation_thread_mag_in_data_x (request, message, &(offset));

      break;
    }
    case attitude_calculation_thread_global_mag_in_data_y:
    {
      __po_hi_unmarshall_request_attitude_calculation_thread_mag_in_data_y (request, message, &(offset));

      break;
    }
    case attitude_calculation_thread_global_mag_in_data_z:
    {
      __po_hi_unmarshall_request_attitude_calculation_thread_mag_in_data_z (request, message, &(offset));

      break;
    }
    case attitude_calculation_thread_global_gyro_in_data_x:
    {
      __po_hi_unmarshall_request_attitude_calculation_thread_gyro_in_data_x (request, message, &(offset));

      break;
    }
    case attitude_calculation_thread_global_gyro_in_data_y:
    {
      __po_hi_unmarshall_request_attitude_calculation_thread_gyro_in_data_y (request, message, &(offset));

      break;
    }
    case attitude_calculation_thread_global_gyro_in_data_z:
    {
      __po_hi_unmarshall_request_attitude_calculation_thread_gyro_in_data_z (request, message, &(offset));

      break;
    }
    default:
    {
      break;
    }
  }
}


