#ifndef __OCARINA_GENERATED_REQUEST_H_
#define __OCARINA_GENERATED_REQUEST_H_ 
#include <types.h>
#include <deployment.h>
/*****************************************************/

/*  This file was automatically generated by Ocarina */

/*  Do NOT hand-modify this file, as your            */

/*  changes will be lost when you re-run Ocarina     */

/*****************************************************/

/*  Enumeration type for all the operations in the distributed application.*/

typedef struct
{
  __po_hi_port_t port;

  union
  {
    struct
    {
      ahrs__data_types__float32_type_aadl accelero_thread_global_acc_in_data_x;

    } accelero_thread_global_acc_in_data_x;

    struct
    {
      ahrs__data_types__float32_type_aadl accelero_thread_global_acc_in_data_y;

    } accelero_thread_global_acc_in_data_y;

    struct
    {
      ahrs__data_types__float32_type_aadl accelero_thread_global_acc_in_data_z;

    } accelero_thread_global_acc_in_data_z;

    struct
    {
      ahrs__data_types__float32_type_aadl accelero_thread_global_acc_out_data_x;

    } accelero_thread_global_acc_out_data_x;

    struct
    {
      ahrs__data_types__float32_type_aadl accelero_thread_global_acc_out_data_y;

    } accelero_thread_global_acc_out_data_y;

    struct
    {
      ahrs__data_types__float32_type_aadl accelero_thread_global_acc_out_data_z;

    } accelero_thread_global_acc_out_data_z;

    struct
    {
      ahrs__data_types__float32_type_aadl magneto_thread_global_mag_in_data_x;

    } magneto_thread_global_mag_in_data_x;

    struct
    {
      ahrs__data_types__float32_type_aadl magneto_thread_global_mag_in_data_y;

    } magneto_thread_global_mag_in_data_y;

    struct
    {
      ahrs__data_types__float32_type_aadl magneto_thread_global_mag_in_data_z;

    } magneto_thread_global_mag_in_data_z;

    struct
    {
      ahrs__data_types__float32_type_aadl magneto_thread_global_mag_out_data_x;

    } magneto_thread_global_mag_out_data_x;

    struct
    {
      ahrs__data_types__float32_type_aadl magneto_thread_global_mag_out_data_y;

    } magneto_thread_global_mag_out_data_y;

    struct
    {
      ahrs__data_types__float32_type_aadl magneto_thread_global_mag_out_data_z;

    } magneto_thread_global_mag_out_data_z;

    struct
    {
      ahrs__data_types__float32_type_aadl gyro_thread_global_gyro_in_data_x;

    } gyro_thread_global_gyro_in_data_x;

    struct
    {
      ahrs__data_types__float32_type_aadl gyro_thread_global_gyro_in_data_y;

    } gyro_thread_global_gyro_in_data_y;

    struct
    {
      ahrs__data_types__float32_type_aadl gyro_thread_global_gyro_in_data_z;

    } gyro_thread_global_gyro_in_data_z;

    struct
    {
      ahrs__data_types__float32_type_aadl gyro_thread_global_gyro_out_data_x;

    } gyro_thread_global_gyro_out_data_x;

    struct
    {
      ahrs__data_types__float32_type_aadl gyro_thread_global_gyro_out_data_y;

    } gyro_thread_global_gyro_out_data_y;

    struct
    {
      ahrs__data_types__float32_type_aadl gyro_thread_global_gyro_out_data_z;

    } gyro_thread_global_gyro_out_data_z;

    struct
    {
      ahrs__data_types__float32_type_aadl attitude_calculation_thread_global_acc_in_data_x;

    } attitude_calculation_thread_global_acc_in_data_x;

    struct
    {
      ahrs__data_types__float32_type_aadl attitude_calculation_thread_global_acc_in_data_y;

    } attitude_calculation_thread_global_acc_in_data_y;

    struct
    {
      ahrs__data_types__float32_type_aadl attitude_calculation_thread_global_acc_in_data_z;

    } attitude_calculation_thread_global_acc_in_data_z;

    struct
    {
      ahrs__data_types__float32_type_aadl attitude_calculation_thread_global_mag_in_data_x;

    } attitude_calculation_thread_global_mag_in_data_x;

    struct
    {
      ahrs__data_types__float32_type_aadl attitude_calculation_thread_global_mag_in_data_y;

    } attitude_calculation_thread_global_mag_in_data_y;

    struct
    {
      ahrs__data_types__float32_type_aadl attitude_calculation_thread_global_mag_in_data_z;

    } attitude_calculation_thread_global_mag_in_data_z;

    struct
    {
      ahrs__data_types__float32_type_aadl attitude_calculation_thread_global_gyro_in_data_x;

    } attitude_calculation_thread_global_gyro_in_data_x;

    struct
    {
      ahrs__data_types__float32_type_aadl attitude_calculation_thread_global_gyro_in_data_y;

    } attitude_calculation_thread_global_gyro_in_data_y;

    struct
    {
      ahrs__data_types__float32_type_aadl attitude_calculation_thread_global_gyro_in_data_z;

    } attitude_calculation_thread_global_gyro_in_data_z;

  } vars;

} __po_hi_request_t;

#define __PO_HI_NB_OPERATIONS 0

#endif
