#include <deployment.h>
#include <po_hi_types.h>
/*****************************************************/
/*  This file was automatically generated by Ocarina */
/*  Do NOT hand-modify this file, as your            */
/*  changes will be lost when you re-run Ocarina     */
/*****************************************************/
const char* __po_hi_ports_names[__PO_HI_NB_PORTS] = {"accelero_thread_global_acc_in_data_x","accelero_thread_global_acc_in_data_y","accelero_thread_global_acc_in_data_z","accelero_thread_global_acc_out_data_x","accelero_thread_global_acc_out_data_y","accelero_thread_global_acc_out_data_z","magneto_thread_global_mag_in_data_x","magneto_thread_global_mag_in_data_y","magneto_thread_global_mag_in_data_z","magneto_thread_global_mag_out_data_x","magneto_thread_global_mag_out_data_y","magneto_thread_global_mag_out_data_z","gyro_thread_global_gyro_in_data_x","gyro_thread_global_gyro_in_data_y","gyro_thread_global_gyro_in_data_z","gyro_thread_global_gyro_out_data_x","gyro_thread_global_gyro_out_data_y","gyro_thread_global_gyro_out_data_z","attitude_calculation_thread_global_acc_in_data_x","attitude_calculation_thread_global_acc_in_data_y","attitude_calculation_thread_global_acc_in_data_z","attitude_calculation_thread_global_mag_in_data_x","attitude_calculation_thread_global_mag_in_data_y","attitude_calculation_thread_global_mag_in_data_z","attitude_calculation_thread_global_gyro_in_data_x","attitude_calculation_thread_global_gyro_in_data_y","attitude_calculation_thread_global_gyro_in_data_z"};

