#ifndef __OCARINA_GENERATED_SUBPROGRAMS_H_
#define __OCARINA_GENERATED_SUBPROGRAMS_H_ 
#include <types.h>
/*****************************************************/

/*  This file was automatically generated by Ocarina */

/*  Do NOT hand-modify this file, as your            */

/*  changes will be lost when you re-run Ocarina     */

/*****************************************************/

void ahrs__subprograms__accelero_sub 
    (ahrs__data_types__float32_type_aadl* acc_out_data_x,
    ahrs__data_types__float32_type_aadl* acc_out_data_y,
    ahrs__data_types__float32_type_aadl* acc_out_data_z);

void ahrs__subprograms__magneto_sub 
    (ahrs__data_types__float32_type_aadl* mag_out_data_x,
    ahrs__data_types__float32_type_aadl* mag_out_data_y,
    ahrs__data_types__float32_type_aadl* mag_out_data_z);

void ahrs__subprograms__gyro_sub 
    (ahrs__data_types__float32_type_aadl* gyro_out_data_x,
    ahrs__data_types__float32_type_aadl* gyro_out_data_y,
    ahrs__data_types__float32_type_aadl* gyro_out_data_z);

void ahrs__subprograms__attitude_sub 
    (ahrs__data_types__float32_type_aadl acc_in_data_x,
    ahrs__data_types__float32_type_aadl mag_in_data_x,
    ahrs__data_types__float32_type_aadl gyro_in_data_x,
    ahrs__data_types__float32_type_aadl acc_in_data_y,
    ahrs__data_types__float32_type_aadl mag_in_data_y,
    ahrs__data_types__float32_type_aadl gyro_in_data_y,
    ahrs__data_types__float32_type_aadl acc_in_data_z,
    ahrs__data_types__float32_type_aadl mag_in_data_z,
    ahrs__data_types__float32_type_aadl gyro_in_data_z);

#endif
