#include "subprograms.h"
#include <types.h>
/*****************************************************/
/*  This file was automatically generated by Ocarina */
/*  Do NOT hand-modify this file, as your            */
/*  changes will be lost when you re-run Ocarina     */
/*****************************************************/
void entryaccelero 
    (ahrs__data_types__float32_type_aadl* acc_out_data_x,
    ahrs__data_types__float32_type_aadl* acc_out_data_y,
    ahrs__data_types__float32_type_aadl* acc_out_data_z);
void ahrs__subprograms__accelero_sub 
    (ahrs__data_types__float32_type_aadl* acc_out_data_x,
    ahrs__data_types__float32_type_aadl* acc_out_data_y,
    ahrs__data_types__float32_type_aadl* acc_out_data_z)
{

  entryaccelero (acc_out_data_x, acc_out_data_y, acc_out_data_z);
}

void entrymagneto 
    (ahrs__data_types__float32_type_aadl* mag_out_data_x,
    ahrs__data_types__float32_type_aadl* mag_out_data_y,
    ahrs__data_types__float32_type_aadl* mag_out_data_z);
void ahrs__subprograms__magneto_sub 
    (ahrs__data_types__float32_type_aadl* mag_out_data_x,
    ahrs__data_types__float32_type_aadl* mag_out_data_y,
    ahrs__data_types__float32_type_aadl* mag_out_data_z)
{

  entrymagneto (mag_out_data_x, mag_out_data_y, mag_out_data_z);
}

void entrygyro 
    (ahrs__data_types__float32_type_aadl* gyro_out_data_x,
    ahrs__data_types__float32_type_aadl* gyro_out_data_y,
    ahrs__data_types__float32_type_aadl* gyro_out_data_z);
void ahrs__subprograms__gyro_sub 
    (ahrs__data_types__float32_type_aadl* gyro_out_data_x,
    ahrs__data_types__float32_type_aadl* gyro_out_data_y,
    ahrs__data_types__float32_type_aadl* gyro_out_data_z)
{

  entrygyro (gyro_out_data_x, gyro_out_data_y, gyro_out_data_z);
}

void entryattitude 
    (ahrs__data_types__float32_type_aadl acc_in_data_x,
    ahrs__data_types__float32_type_aadl mag_in_data_x,
    ahrs__data_types__float32_type_aadl gyro_in_data_x,
    ahrs__data_types__float32_type_aadl acc_in_data_y,
    ahrs__data_types__float32_type_aadl mag_in_data_y,
    ahrs__data_types__float32_type_aadl gyro_in_data_y,
    ahrs__data_types__float32_type_aadl acc_in_data_z,
    ahrs__data_types__float32_type_aadl mag_in_data_z,
    ahrs__data_types__float32_type_aadl gyro_in_data_z);
void ahrs__subprograms__attitude_sub 
    (ahrs__data_types__float32_type_aadl acc_in_data_x,
    ahrs__data_types__float32_type_aadl mag_in_data_x,
    ahrs__data_types__float32_type_aadl gyro_in_data_x,
    ahrs__data_types__float32_type_aadl acc_in_data_y,
    ahrs__data_types__float32_type_aadl mag_in_data_y,
    ahrs__data_types__float32_type_aadl gyro_in_data_y,
    ahrs__data_types__float32_type_aadl acc_in_data_z,
    ahrs__data_types__float32_type_aadl mag_in_data_z,
    ahrs__data_types__float32_type_aadl gyro_in_data_z)
{

  entryattitude (acc_in_data_x, mag_in_data_x, gyro_in_data_x, acc_in_data_y, mag_in_data_y, gyro_in_data_y, acc_in_data_z, mag_in_data_z, gyro_in_data_z);
}


