#ifndef __OCARINA_GENERATED_TYPES_H_
#define __OCARINA_GENERATED_TYPES_H_ 
#include <po_hi_types.h>
/*****************************************************/

/*  This file was automatically generated by Ocarina */

/*  Do NOT hand-modify this file, as your            */

/*  changes will be lost when you re-run Ocarina     */

/*****************************************************/

typedef __po_hi_float32_t ahrs__data_types__float32_type_aadl;

#endif
